#!/usr/bin/env bash

set -eu
set -o pipefail

SLEEPLIGHT_SERVER_PATH=/home/pi/sleeplight
REMOTE=${1:-}

if [ -z "$REMOTE" ]; then
	# Push up any local changes
	git push
	# build the client
	npm run build
	# Clean up the remote client
	ssh sleeplight "rm -rf $SLEEPLIGHT_SERVER_PATH/client/*"
	# Push the client to remote
	scp -r ./client/* "sleeplight:$SLEEPLIGHT_SERVER_PATH/client/"
	# Run the remote deploy script
	ssh sleeplight "cd $SLEEPLIGHT_SERVER_PATH; git pull; ./deploy remote"
else
    # REMOTE: Install any package changes
	npm install --production
	# REMOTE: Copy over the Upstart config
  	sudo cp ./sleeplight.conf /etc/init/sleeplight.conf
  	# REMOTE: Restart the server
  	sudo restart sleeplight
fi
